name: Publish to Personal Website Client Repository

on:
  push:
    branches: [ "main" ]

env:
  GITHUB_TOKEN: "${{ secrets.API_TOKEN_GITHUB }}"
  GITHUB_USER: "${{ secrets.USER_NAME }}"
  GITHUB_EMAIL: "${{ secrets.USER_EMAIL }}"
  TARGET_REPO: "https://github.com/nightmaregaurav/personal-website-client.git"
  TARGET_BRANCH: "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.7.0]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: yarn install
      - run: npm run build --if-present
      - run: git config --global user.name $GITHUB_USER
      - run: git config --global user.email $GITHUB_EMAIL
      - run: git clone $TARGET_REPO --branch $TARGET_BRANCH --single-branch target_repo
      - run: chmod 755 publish.sh
      - run: ./publish.sh