name: Publish to Personal Website Client Repository

on:
  push:
    branches: [ "main" ]

env:
  TARGET_REPO: ${{ secrets.TARGET_REPO }}
  TARGET_REPO_BRANCH: ${{ secrets.TARGET_REPO_BRANCH }}
  TARGET_REPO_USER: ${{ secrets.TARGET_REPO_USER }}
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.7.0]

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'

      - run: echo "Publishing V${{ steps.version.outputs.value }}"
      - run: yarn install
      - run: npm run build

      - run: git config --global user.name ${{github.actor}}
      - run: git config --global user.email ${{github.actor}}@users.noreply.github.com
      - run: git clone https://${TOKEN}@github.com/${TARGET_REPO_USER}/${TARGET_REPO}.git --branch ${TARGET_REPO_BRANCH} --single-branch target_repo

      - run: mkdir -p destination_repo
      - run: cp -r target_repo/.git destination_repo/
      - run: cp -r build/* destination_repo
      - run: cp -r build/* destination_repo
      - run: cp -r client-data/* destination_repo

      - run: cd destination_repo && git add --all
      - run: cd destination_repo && git commit -m "Automated Release | V${{ steps.version.outputs.value }}"
      - run: cd destination_repo && git remote add github-token "https://${TOKEN}@github.com/${TARGET_REPO_USER}/${TARGET_REPO}.git"
      - run: git config --unset-all http.https://github.com/.extraheader
      - run: cd destination_repo && git push github-token ${TARGET_REPO_BRANCH}
